let atributeImages = {
    bald: "👨‍🦲",
    male: "♂️",
    glasses: "👓",
    hat: "👒",
    beard: "🧔",
    moustache: "👨",
    "chin-beard": "🧔🏽",
    "white hair": "👵",
    "blond hair": "👱‍♀️",
    "red hair": "👨‍🦰",
    "brown hair": "🧑‍",
    "black hair": "👩🏻‍🦱",
    "blue eyes": "👁️‍🗨️",
    "big nose": "👃",
    "sunglasses":"🕶️"
  },
  people = {
    Alex: {
      bald: false,
      male: true,
      glasses: false,
      hat: false,
      beard: true,
      moustache: true,
      "chin-beard": false,
      "white hair": false,
      "blond hair": false,
      "red hair": false,
      "brown hair": false,
      "black hair": true,
      "blue eyes": false,
      "big nose": false,
      "sunglasses": false
    },
    Anita: {
      bald: false,
      male: false,
      glasses: false,
      hat: false,
      beard: false,
      moustache: false,
      "chin-beard": false,
      "white hair": false,
      "blond hair": true,
      "red hair": false,
      "brown hair": false,
      "black hair": false,
      "blue eyes": true,
      "big nose": false,
      "sunglasses": false
    },
    Peter: {
      bald: false,
      male: true,
      glasses: false,
      hat: false,
      beard: false,
      moustache: false,
      "chin-beard": false,
      "white hair": true,
      "blond hair": false,
      "red hair": false,
      "brown hair": false,
      "black hair": false,
      "blue eyes": true,
      "big nose": true,
      "sunglasses": false
    },
    Eric: {
      bald: false,
      male: true,
      glasses: false,
      hat: true,
      beard: false,
      moustache: false,
      "chin-beard": false,
      "white hair": false,
      "blond hair": true,
      "red hair": false,
      "brown hair": false,
      "black hair": false,
      "blue eyes": false,
      "big nose": false,
      "sunglasses": false
    },
    Charles: {
      bald: false,
      male: true,
      glasses: false,
      hat: false,
      beard: true,
      moustache: true,
      "chin-beard": false,
      "white hair": false,
      "blond hair": true,
      "red hair": false,
      "brown hair": false,
      "black hair": false,
      "blue eyes": false,
      "big nose": false,
      "sunglasses": false
    },
    Sam: {
      bald: true,
      male: true,
      glasses: true,
      hat: false,
      beard: false,
      moustache: false,
      "chin-beard": false,
      "white hair": true,
      "blond hair": false,
      "red hair": false,
      "brown hair": false,
      "black hair": false,
      "blue eyes": false,
      "big nose": false,
      "sunglasses": false
    },
    Joe: {
      bald: false,
      male: true,
      glasses: true,
      hat: false,
      beard: false,
      moustache: false,
      "chin-beard": false,
      "white hair": false,
      "blond hair": true,
      "red hair": false,
      "brown hair": false,
      "black hair": false,
      "blue eyes": false,
      "big nose": false,
      "sunglasses": false
    },
    Maria: {
      bald: false,
      male: false,
      glasses: false,
      hat: true,
      beard: false,
      moustache: false,
      "chin-beard": false,
      "white hair": false,
      "blond hair": false,
      "red hair": false,
      "brown hair": true,
      "black hair": false,
      "blue eyes": false,
      "big nose": false,
      "sunglasses": false
    },
    Philip: {
      bald: false,
      male: true,
      glasses: false,
      hat: false,
      beard: true,
      moustache: false,
      "chin-beard": true,
      "white hair": false,
      "blond hair": false,
      "red hair": false,
      "brown hair": false,
      "black hair": true,
      "blue eyes": false,
      "big nose": false,
      "sunglasses": false
    },
    Richard: {
      bald: true,
      male: true,
      glasses: false,
      hat: false,
      beard: true,
      moustache: true,
      "chin-beard": true,
      "white hair": false,
      "blond hair": false,
      "red hair": false,
      "brown hair": true,
      "black hair": false,
      "blue eyes": false,
      "big nose": false,
      "sunglasses": false
    },
    Susan: {
      bald: false,
      male: false,
      glasses: false,
      hat: false,
      beard: false,
      moustache: false,
      "chin-beard": false,
      "white hair": true,
      "blond hair": false,
      "red hair": false,
      "brown hair": false,
      "black hair": false,
      "blue eyes": false,
      "big nose": false,
      "sunglasses": false
    },
    Max: {
      bald: false,
      male: true,
      glasses: false,
      hat: false,
      beard: true,
      moustache: true,
      "chin-beard": false,
      "white hair": false,
      "blond hair": false,
      "red hair": false,
      "brown hair": true,
      "black hair": false,
      "blue eyes": false,
      "big nose": true,
      "sunglasses": false
    },
    Alfred: {
      bald: false,
      male: true,
      glasses: false,
      hat: false,
      beard: true,
      moustache: true,
      "chin-beard": false,
      "white hair": false,
      "blond hair": false,
      "red hair": true,
      "brown hair": false,
      "black hair": false,
      "blue eyes": true,
      "big nose": false,
      "sunglasses": false
    },
    Robert: {
      bald: false,
      male: true,
      glasses: false,
      hat: false,
      beard: false,
      moustache: false,
      "chin-beard": false,
      "white hair": false,
      "blond hair": false,
      "red hair": false,
      "brown hair": true,
      "black hair": false,
      "blue eyes": true,
      "big nose": true,
      "sunglasses": false
    },
    Frans: {
      bald: false,
      male: true,
      glasses: false,
      hat: false,
      beard: false,
      moustache: false,
      "chin-beard": false,
      "white hair": false,
      "blond hair": false,
      "red hair": true,
      "brown hair": false,
      "black hair": false,
      "blue eyes": false,
      "big nose": false,
      "sunglasses": false
    },
    Claire: {
      bald: false,
      male: false,
      glasses: true,
      hat: true,
      beard: false,
      moustache: false,
      "chin-beard": false,
      "white hair": false,
      "blond hair": false,
      "red hair": true,
      "brown hair": false,
      "black hair": false,
      "blue eyes": false,
      "big nose": false,
      "sunglasses": false
    },
    Paul: {
      bald: false,
      male: true,
      glasses: true,
      hat: false,
      beard: false,
      moustache: false,
      "chin-beard": false,
      "white hair": true,
      "blond hair": false,
      "red hair": false,
      "brown hair": false,
      "black hair": false,
      "blue eyes": false,
      "big nose": false,
      "sunglasses": false
    },
    Bill: {
      bald: true,
      male: true,
      glasses: false,
      hat: false,
      beard: true,
      moustache: false,
      "chin-beard": true,
      "white hair": false,
      "blond hair": false,
      "red hair": true,
      "brown hair": false,
      "black hair": false,
      "blue eyes": false,
      "big nose": false,
      "sunglasses": false
    },
    David: {
      bald: false,
      male: true,
      glasses: false,
      hat: false,
      beard: true,
      moustache: false,
      "chin-beard": true,
      "white hair": false,
      "blond hair": true,
      "red hair": false,
      "brown hair": false,
      "black hair": false,
      "blue eyes": false,
      "big nose": false,
      "sunglasses": false
    },
    Bernard: {
      bald: false,
      male: true,
      glasses: false,
      hat: true,
      beard: false,
      moustache: false,
      "chin-beard": false,
      "white hair": false,
      "blond hair": false,
      "red hair": false,
      "brown hair": true,
      "black hair": false,
      "blue eyes": false,
      "big nose": true,
      "sunglasses": false
    },
    George: {
      bald: false,
      male: true,
      glasses: false,
      hat: true,
      beard: false,
      moustache: false,
      "chin-beard": false,
      "white hair": true,
      "blond hair": false,
      "red hair": false,
      "brown hair": false,
      "black hair": false,
      "blue eyes": false,
      "big nose": false,
      "sunglasses": false
    },
    Tom: {
      bald: true,
      male: true,
      glasses: true,
      hat: false,
      beard: false,
      moustache: false,
      "chin-beard": false,
      "white hair": false,
      "blond hair": false,
      "red hair": false,
      "brown hair": false,
      "black hair": true,
      "blue eyes": true,
      "big nose": false,
      "sunglasses": false
    },
    Herman: {
      bald: true,
      male: true,
      glasses: false,
      hat: false,
      beard: false,
      moustache: false,
      "chin-beard": false,
      "white hair": false,
      "blond hair": false,
      "red hair": true,
      "brown hair": false,
      "black hair": false,
      "blue eyes": false,
      "big nose": true,
      "sunglasses": false
    },
    Anne: {
      bald: false,
      male: false,
      glasses: false,
      hat: false,
      beard: false,
      moustache: false,
      "chin-beard": false,
      "white hair": false,
      "blond hair": false,
      "red hair": false,
      "brown hair": false,
      "black hair": true,
      "blue eyes": false,
      "big nose": false,
      "sunglasses": false
    },
    // Custom *************************
  Cesar: {
    "bald": false,
    "male": true,
    "glasses": false,
    "hat": false,
    "beard": false,
    "moustache": false,
    "chin-beard": false,
    "white hair": false,
    "blond hair": false,
    "red hair": false,
    "brown hair": false,
    "black hair": true,
    "blue eyes": true,
    "big nose": false,
    "sunglasses": false
  },
  Olivia: {
    "bald": false,
    "male": false,
    "glasses": true,
    "hat": false,
    "beard": false,
    "moustache": false,
    "chin-beard": false,
    "white hair": false,
    "blond hair": true,
    "red hair": false,
    "brown hair": false,
    "black hair": false,
    "blue eyes": false,
    "big nose": false,
    "sunglasses": false
  },
  John: {
    "bald": false,
    "male": true,
    "glasses": false,
    "hat": false,
    "beard": false,
    "moustache": false,
    "chin-beard": false,
    "white hair": false,
    "blond hair": false,
    "red hair": false,
    "brown hair": false,
    "black hair": true,
    "blue eyes": false,
    "big nose": false,
    "sunglasses": true
  },
  Noah: {
    "bald": false,
    "male": true,
    "glasses": false,
    "hat": false,
    "beard": false,
    "moustache": false,
    "chin-beard": false,
    "white hair": true,
    "blond hair": false,
    "red hair": false,
    "brown hair": false,
    "black hair": false,
    "blue eyes": false,
    "big nose": false,
    "sunglasses": false
  },
  Ricky: {
    "bald": false,
    "male": true,
    "glasses": false,
    "hat": false,
    "beard": false,
    "moustache": false,
    "chin-beard": false,
    "white hair": false,
    "blond hair": true,
    "red hair": false,
    "brown hair": false,
    "black hair": false,
    "blue eyes": false,
    "big nose": false,
    "sunglasses": true
  },
  Travis: {
    "bald": false,
    "male": true,
    "glasses": false,
    "hat": false,
    "beard": true,
    "moustache": false,
    "chin-beard": true,
    "white hair": false,
    "blond hair": true,
    "red hair": false,
    "brown hair": false,
    "black hair": false,
    "blue eyes": true,
    "big nose": false,
    "sunglasses": false
  },
  Samuel: {
    "bald": false,
    "male": true,
    "glasses": false,
    "hat": false,
    "beard": true,
    "moustache": false,
    "chin-beard": true,
    "white hair": true,
    "blond hair": false,
    "red hair": false,
    "brown hair": false,
    "black hair": false,
    "blue eyes": false,
    "big nose": false,
    "sunglasses": false
  },
  Henry: {
    "bald": false,
    "male": true,
    "glasses": false,
    "hat": false,
    "beard": true,
    "moustache": true,
    "chin-beard": false,
    "white hair": false,
    "blond hair": true,
    "red hair": false,
    "brown hair": false,
    "black hair": false,
    "blue eyes": false,
    "big nose": false,
    "sunglasses": true
  },
  Luna: {
    "bald": false,
    "male": false,
    "glasses": false,
    "hat": false,
    "beard": false,
    "moustache": false,
    "chin-beard": false,
    "white hair": false,
    "blond hair": false,
    "red hair": false,
    "brown hair": true,
    "black hair": false,
    "blue eyes": true,
    "big nose": false,
    "sunglasses": false
  },
  Carter: {
    "bald": false,
    "male": true,
    "glasses": true,
    "hat": false,
    "beard": false,
    "moustache": false,
    "chin-beard": false,
    "white hair": false,
    "blond hair": false,
    "red hair": false,
    "brown hair": false,
    "black hair": true,
    "blue eyes": false,
    "big nose": false,
    "sunglasses": false
  },
  Elias: {
    "bald": false,
    "male": true,
    "glasses": false,
    "hat": false,
    "beard": true,
    "moustache": false,
    "chin-beard": true,
    "white hair": false,
    "blond hair": false,
    "red hair": false,
    "brown hair": true,
    "black hair": false,
    "blue eyes": false,
    "big nose": false,
    "sunglasses": false
  },
  Emily: {
    "bald": false,
    "male": false,
    "glasses": false,
    "hat": false,
    "beard": false,
    "moustache": false,
    "chin-beard": false,
    "white hair": false,
    "blond hair": true,
    "red hair": false,
    "brown hair": false,
    "black hair": false,
    "blue eyes": false,
    "big nose": false,
    "sunglasses": false
  },
  Santiago: {
    "bald": false,
    "male": true,
    "glasses": false,
    "hat": false,
    "beard": true,
    "moustache": true,
    "chin-beard": false,
    "white hair": false,
    "blond hair": false,
    "red hair": false,
    "brown hair": true,
    "black hair": false,
    "blue eyes": false,
    "big nose": false,
    "sunglasses": true
  },
  Ethan: {
    "bald": false,
    "male": true,
    "glasses": false,
    "hat": false,
    "beard": false,
    "moustache": false,
    "chin-beard": false,
    "white hair": false,
    "blond hair": false,
    "red hair": true,
    "brown hair": false,
    "black hair": false,
    "blue eyes": false,
    "big nose": false,
    "sunglasses": true
  },
  Lucas: {
    "bald": false,
    "male": true,
    "glasses": false,
    "hat": false,
    "beard": false,
    "moustache": false,
    "chin-beard": false,
    "white hair": false,
    "blond hair": false,
    "red hair": false,
    "brown hair": true,
    "black hair": false,
    "blue eyes": true,
    "big nose": false,
    "sunglasses": false
  },
  Wesley: {
    "bald": false,
    "male": true,
    "glasses": false,
    "hat": false,
    "beard": true,
    "moustache": false,
    "chin-beard": true,
    "white hair": false,
    "blond hair": false,
    "red hair": true,
    "brown hair": false,
    "black hair": false,
    "blue eyes": false,
    "big nose": false,
    "sunglasses": false
  },
  Hunter: {
    "bald": false,
    "male": true,
    "glasses": false,
    "hat": false,
    "beard": false,
    "moustache": false,
    "chin-beard": false,
    "white hair": false,
    "blond hair": false,
    "red hair": true,
    "brown hair": false,
    "black hair": false,
    "blue eyes": true,
    "big nose": false,
    "sunglasses": false
  },
  Mark: {
    "bald": false,
    "male": true,
    "glasses": false,
    "hat": false,
    "beard": true,
    "moustache": true,
    "chin-beard": true,
    "white hair": true,
    "blond hair": false,
    "red hair": false,
    "brown hair": false,
    "black hair": false,
    "blue eyes": false,
    "big nose": false,
    "sunglasses": false
  },
  Dylan: {
    "bald": true,
    "male": true,
    "glasses": false,
    "hat": false,
    "beard": true,
    "moustache": false,
    "chin-beard": true,
    "white hair": false,
    "blond hair": false,
    "red hair": true,
    "brown hair": false,
    "black hair": false,
    "blue eyes": false,
    "big nose": false,
    "sunglasses": true
  },
  Austin: {
    "bald": false,
    "male": true,
    "glasses": false,
    "hat": false,
    "beard": true,
    "moustache": true,
    "chin-beard": true,
    "white hair": false,
    "blond hair": true,
    "red hair": false,
    "brown hair": false,
    "black hair": false,
    "blue eyes": false,
    "big nose": false,
    "sunglasses": false
  },
  Tyler: {
    "bald": false,
    "male": true,
    "glasses": false,
    "hat": false,
    "beard": false,
    "moustache": false,
    "chin-beard": false,
    "white hair": false,
    "blond hair": false,
    "red hair": false,
    "brown hair": true,
    "black hair": false,
    "blue eyes": false,
    "big nose": false,
    "sunglasses": true
  },
  Miguel: {
    "bald": false,
    "male": true,
    "glasses": false,
    "hat": false,
    "beard": false,
    "moustache": false,
    "chin-beard": false,
    "white hair": true,
    "blond hair": false,
    "red hair": false,
    "brown hair": false,
    "black hair": false,
    "blue eyes": false,
    "big nose": false,
    "sunglasses": true
  },
  Derek: {
    "bald": true,
    "male": true,
    "glasses": true,
    "hat": false,
    "beard": false,
    "moustache": false,
    "chin-beard": false,
    "white hair": false,
    "blond hair": false,
    "red hair": false,
    "brown hair": false,
    "black hair": true,
    "blue eyes": false,
    "big nose": false,
    "sunglasses": false
  },
  Julia: {
    "bald": false,
    "male": false,
    "glasses": false,
    "hat": false,
    "beard": false,
    "moustache": false,
    "chin-beard": false,
    "white hair": false,
    "blond hair": false,
    "red hair": true,
    "brown hair": false,
    "black hair": false,
    "blue eyes": false,
    "big nose": false,
    "sunglasses": false
  },
  Adeline: {
    "bald": false,
    "male": false,
    "glasses": false,
    "hat": false,
    "beard": false,
    "moustache": false,
    "chin-beard": false,
    "white hair": true,
    "blond hair": false,
    "red hair": false,
    "brown hair": false,
    "black hair": false,
    "blue eyes": true,
    "big nose": false,
    "sunglasses": false
  },
  Sara: {
    "bald": false,
    "male": false,
    "glasses": true,
    "hat": false,
    "beard": false,
    "moustache": false,
    "chin-beard": false,
    "white hair": false,
    "blond hair": false,
    "red hair": false,
    "brown hair": false,
    "black hair": true,
    "blue eyes": false,
    "big nose": false,
    "sunglasses": false
  },
  total: {
    bald: 0,
    male: 0,
    "normal glasses": 0,
    "sunglasses": 0,
    hat: 0,
    beard: 0,
    moustache: 0,
    "chin-beard": 0,
    "white hair": 0,
    "blond hair": 0,
    "red hair": 0,
    "brown hair": 0,
    "black hair": 0,
    "blue eyes": 0,
    "big nose": 0
  }
  };